name: Icon Request
description: Request a new icon.
title: "[Icon Request]: "
labels: [Icon Request]
assigness:
  - WalkxCode
body:
  - type: markdown
    attributes:
      value: |
        Thanks for contributing and requesting a new icon!
  - type: input
    id: name
    attributes:
      label: Icon Name
      description: What is the name of the icon?
      placeholder: [Example: Portainer]
    validations:
      required: true
  - type: input
      label: Icon Source
      description: What is the website/page of the service?
      placeholder: [Example: https://www.portainer.io/]
    validations:
      required: true
  - type: markdown
    attributes:
      value: Upload the icon [Optional]:
  - type: dropdown
    id: file
    attributes:
      label: PNG or SVG? [Optional]
      multiple: true
      options:
        - PNG
        - SVG
    validations:
      required: false
